variables: #varibales déclaré valable pour tout le pipline
  APP_NAME: adda-staticwebsite 
  REVIEW_APP_NAME: adda-${CI_COMMIT_REF_NAME}
  IP_EAZY: ip10-0-2-3-cihiqkh906p0qa3dugi0
  REPOSITORY_ADRESS: direct.docker.labs.eazytraining.fr
  API_PORT: 1993
  API_ENDPOINT: ${IP_EAZY}-${API_PORT}.${REPOSITORY_ADRESS}
  INTERNAL_PORT: 80
  TEST_PORT: 90
  STG_EXTERNAL_PORT: 8080
  PROD_EXTERNAL_PORT: 80
  CONTAINER_IMAGE: ${IMAGE_NAME}:${CI_COMMIT_REF_NAME}

image: docker:latest #image a utiliser pour l'executuion des stages 
services:
  - name: docker:dind # le type de service docker in docker pour faciliter la creation des conteneur et permetre la connexion entre eux
    alias: docker


stages: # les étape de la pipline et l'ordre de l'execution
  - build
  - Test acceptation
  - Release image
  - Deploy review
  - Stop review
  - Deploy staging
  - Test staging  
  - Deploy prod
  - Test prod

.test_template: &test
  image: alpine
  script:
    - apk --no-cache add curl
    - curl -k "https://$DOMAIN" | grep -i "dimension"

.docker-build: #creation de l'image par l'utilisation du Dockerfile du repository
  # Use the official docker image.
  stage: build
  script:
    - docker build -t  ${APP_NAME} .
    - docker save ${APP_NAME} > ${APP_NAME}.tar
  artifacts: # enregistrer l'image buildé pour la suite , cette étape est essentiel pour rendre l'image disponoble pour le reste du pipeline
    paths:
      - ${APP_NAME}.tar    


.test acceptation: #tester le bon fonctionnement de l'application contenerisée 
  # Official docker image.
  stage: Test acceptation
  script:
    - docker load < ${APP_NAME}.tar
    - docker run -d -p ${TEST_PORT}:${INTERNAL_PORT} --name webapp ${APP_NAME}
    - apk --no-cache add curl
    - sleep 5
    - curl "http://docker:${TEST_PORT}" | grep -i "dimension"

.release image: # l'enregistrement de l'image de l'application dans le registry de Gitlab apes le test
  stage: Release image
  script:
    - docker load < ${APP_NAME}.tar
    - docker tag ${APP_NAME} ${IMAGE_NAME}:${CI_COMMIT_REF_NAME}
    - docker tag ${APP_NAME} "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
    - docker push "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"

.deploy staging: 
  stage: Deploy staging
  environment:
    name: staging
    url: http://${IP_EAZY}-${STG_EXTERNAL_PORT}.${REPOSITORY_ADRESS}
  only : 
    - master
  script:
    - apk --no-cache add curl
    - 'curl -v -X POST http://${API_ENDPOINT}/staging -H "Content-Type: application/json" -d "{\"your_name\":\"${APP_NAME}\",\"container_image\":\"${CONTAINER_IMAGE}\", \"external_port\":\"${STG_EXTERNAL_PORT}\", \"internal_port\":\"${INTERNAL_PORT}\"}"  2>&1 | grep 200'


deploy prod: #déployement de l'application pour la partie production ( client final ou le consommateur der l'application ) 
  stage: Deploy prod
  environment:
    name: prod
    url: http://${IP_EAZY}-${PROD_EXTERNAL_PORT}.${REPOSITORY_ADRESS}
  only:
    - master
  script:
    - apk --no-cache add curl
    - 'curl -v -X POST http://${API_ENDPOINT}/prod -H "Content-Type: application/json" -d "{\"your_name\":\"${APP_NAME}\",\"container_image\":\"${CONTAINER_IMAGE}\", \"external_port\":\"${PROD_EXTERNAL_PORT}\", \"internal_port\":\"${INTERNAL_PORT}\"}"  2>&1 | grep 200'

.deploy review:
  stage: Deploy review
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://${REVIEW_APP_ENDPOINT}
    on_stop: stop review
  only:
    - merge_requests
  variables:
    APP_NAME: ${REVIEW_APP_NAME}
  script:
    - apk --no-cache add curl
    - echo $APP_NAME
    - 'curl -X POST http://${REVIEW_API_ENDPOINT}/review -H "Content-Type: application/json" -d "{\"your_name\":\"${APP_NAME}\",\"container_image\":\"${CONTAINER_IMAGE}\", \"external_port\":\"${EXTERNAL_PORT}\", \"internal_port\":\"${INTERNAL_PORT}\"}"'

.stop review:
  stage: Stop review
  variables:
    GIT_STRATEGY: none
    APP_NAME: ${REVIEW_APP_NAME}
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  only:
    - merge_requests
  when: manual  
  script:
    - apk --no-cache add curl
    - 'curl -X DELETE http://${REVIEW_API_ENDPOINT}/review -H "Content-Type: application/json" -d "{\"your_name\":\"${APP_NAME}\"}"'

test staging:
  <<: *test
  stage: Test staging
  only:
  - master
  variables:
    DOMAIN: ${IP_EAZY}-${STG_EXTERNAL_PORT}.${REPOSITORY_ADRESS}


test prod:
  <<: *test
  stage: Test prod
  only:
    - master  
  variables:
    DOMAIN: ${IP_EAZY}-${PROD_EXTERNAL_PORT}.${REPOSITORY_ADRESS}
