variables:
  EAZYLABS_IP: ip10-0-3-3-cgts7j2bihn0qm0bq130
  APP_NAME: ulrich-staticwebsite
  EAZYLABS_DOMAIN: direct.docker.labs.eazytraining.fr  
  API_PORT: "1993"
  API_ENDPOINT: ${EAZYLABS_IP}-${API_PORT}.${EAZYLABS_DOMAIN}
  INTERNAL_PORT: 80
  STG_EXTERNAL_PORT: 8080
  PROD_EXTERNAL_PORT: 80
  REVIEW_EXTERNAL_PORT: 8000
  TEST_PORT: 90
  CONTAINER_IMAGE: ${IMAGE_NAME}:${CI_COMMIT_REF_NAME}

image: docker:latest
services:
  - name: docker:dind
    alias: docker

stages:
  - Build image
  - Test acceptation
  - Release image
  - Deploy review
  - Stop review
  - Deploy staging
  - Test staging
  - Deploy prod
  - Test prod


docker-build:
  stage: Build image
  script:
    - docker build -t ${APP_NAME} .
    - docker save ${APP_NAME} > ${APP_NAME}.tar
  artifacts:
    paths:
      - "${APP_NAME}.tar"
    when: on_success
    expire_in: 2 days

test acceptation:
  stage: Test acceptation
  script:
    - docker load < ${APP_NAME}.tar
    - docker run -d -p ${TEST_PORT}:${INTERNAL_PORT}  --name webapp ${APP_NAME}
    - apk --no-cache add curl
    - sleep 5
    - curl "http://docker:${TEST_PORT}" | grep -i "Dimension"

